import esbuild from "esbuild";
import process from "process";
import path from "node:path";
import { copyFile, lstat, mkdir, readFile, unlink } from "node:fs/promises";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const manifest = JSON.parse(await readFile("manifest.json", "utf8"));
const defaultDevPluginDir = path.resolve(
	process.cwd(),
	"..",
	"convex-sync",
	".obsidian",
	"plugins",
	manifest.id,
);
const defaultDevPluginDirs = [
	defaultDevPluginDir,
	path.resolve(
		process.env.HOME ?? "/home/shlok",
		"Downloads",
		"convex-sync",
		".obsidian",
		"plugins",
		manifest.id,
	),
];
const devPluginDirs = (
	process.env.OBSIDIAN_PLUGIN_DEV_DIRS ??
	process.env.OBSIDIAN_PLUGIN_DEV_DIR ??
	defaultDevPluginDirs.join(path.delimiter)
)
	.split(path.delimiter)
	.map((pluginDir) => pluginDir.trim())
	.filter((pluginDir) => pluginDir.length > 0);

async function copyArtifactsToVault() {
	if (devPluginDirs.length === 0) {
		return;
	}
	for (const devPluginDir of devPluginDirs) {
		await mkdir(devPluginDir, { recursive: true });
		for (const artifact of ["main.js", "manifest.json", "styles.css"]) {
			const destination = path.join(devPluginDir, artifact);
			try {
				const stat = await lstat(destination).catch(() => null);
				if (stat?.isSymbolicLink()) {
					await unlink(destination);
				}
				await copyFile(artifact, destination);
			} catch (error) {
				if (
					error &&
					typeof error === "object" &&
					"code" in error &&
					error.code === "ENOENT"
				) {
					continue;
				}
				throw error;
			}
		}
		console.log(`[obsidian-convex-sync] copied artifacts to ${devPluginDir}`);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		{
			name: "copy-obsidian-artifacts",
			setup(build) {
				build.onEnd(async (result) => {
					if (result.errors.length > 0) {
						return;
					}
					await copyArtifactsToVault();
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
